"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

NAME = 'Subterraneman'
VERSION = '1.0'

plist = dict(
    CFBundleName=NAME,
    CFBundleShortVersionString=VERSION,
    CFBundleGetInfoString=' '.join([NAME, VERSION]),
    CFBundleExecutable=NAME,
)


APP = [ dict(script='run_game.py', plist=plist) ]
DATA_FILES = [ 'English.lproj', 'data', 'lib', 'levels']
OPTIONS = {'argv_emulation': True, 'includes': ['pygame']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
